name = "Ballsnia"
author = "Jack Duffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a110e60dee3f6d242b41ba005ef8ddefeb5869fe698868eeb6496f9358ffa95"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
