name = "Ballsnia"
author = "Jack Duffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bed66eb2cfb6ff0998aa426855d265a1cbebdaa48839a38417f77495a9e25125"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
