name = "Ballsnia"
author = "Jack Duffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ede4684fcbf2c2a10462452f7e17d1e4cb0e94e98fa587574045454bf077682"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
